name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install sshpass
        run: |
          sudo apt-get update -y
          sudo apt-get install -y sshpass

      - name: Deploy to VPS
        run: |
          sshpass -p ${{ secrets.SERVER_PASSWORD }} ssh tim1@nextgen.dev.smartgreenovation.com 'bash -s' < deploy.sh
